### ISSUE TITLE
Add AutoSurvey and GraphRAG

### ISSUE THREAD

**Issue by impredicative** [kyrolabs/awesome-agents#7]
Add these for topic report generation:

* https://github.com/AutoSurveys/AutoSurvey
* https://github.com/microsoft/graphrag

I don't know how your classification system works, so I don't know where to place it.

**Comment by sbusso** [comment]
@impredicative, thanks for the suggestions. I did consider Graphrag before, but it is not agentic. AutoSurvey is also very close to a RAG pipeline, but with the output and evaluation it adds agentic value, maybe for Knowledge Managemen or Automation?

**Comment by sbusso** [comment]
To be “agentic” means that a system or tool can perform tasks or make decisions autonomously without constant human input. A non-agentic tool, like RAG, assists in tasks (e.g., enhancing responses with retrieved information) but requires explicit instructions and doesn’t act on its own.

**Comment by sbusso** [comment]
RAGs are not agent

**Comment by sbusso** [comment]
"GraphRAG is a structured, hierarchical approach to Retrieval Augmented Generation (RAG)"

**Comment by sbusso** [comment]
The definition above is unrelated to semantic search and is not based on dislike or hate of RAG. RAG are tools used in various generative LLM use cases, including agents, pipelines, or other programs. This list aims for projects that are agents first or primarily focused on providing building blocks to build agents specifically. It is not meant to list all the AI tools, which are likely found in many other AI lists. The list may have some counterexamples as it has evolved over a year, and the number of agentic-centric projects has grown significantly.

**Comment by sbusso** [comment]
PS: the definition above that you disliked is the first definition provided by the link you shared

**Comment by sbusso** [comment]
I read that, and as it states, the goal of this framework is to provide a technique to retrieve content from a knowledge graph db, and then provide the content to QA pipeline. Which is inline with my comment here https://github.com/kyrolabs/awesome-agents/issues/7#issuecomment-2299960553
